### ISSUE TITLE
docker-compose binary arch is hardcoded

### ISSUE THREAD

**Issue by yangm97** [geerlingguy/ansible-role-docker#145]
Currently this role downloads x86_64 docker-compose binaries regardless of what your system is running or `docker_apt_arch`.

**Comment by DWSR** [comment]
Yeah, just ran into this when installing on a Raspberry Pi.

This appears to be because only `x86_64` binaries are published by that project. Additionally, the "run as a container" option that's outlined [in the Docker docs](https://docs.docker.com/compose/install/#install-as-a-container) cannot be used on non `x86_64` architectures because the container images are only published for `amd64`. It looks like the only way to use `docker-compose` on non `x86_64` architectures is to use `pip`.

**Comment by geerlingguy** [comment]
For ARM platforms, I maintain a separate role: https://github.com/geerlingguy/ansible-role-docker_arm

Trying to support both ARM and AMD64 in one role is not very fun (I tried a couple times).

**Comment by danmilon** [comment]
I bumped into this too. Got a bit misled by `docker_apt_arch`, thinking that it fully supported non x86-64 arches.
