### ISSUE TITLE
ansible-lint warn

### ISSUE THREAD

**Issue by jamel-hrt** [geerlingguy/ansible-role-docker#191]
Hi

When we use ansible-lint to check the role, there is this warning.
ansible-lint version : 4.2.0
geerlingguy.docker version : 2.7.0
```
$ ansible-lint roles/geerlingguy.docker/
[306] Shells that use pipes should set the pipefail option
roles/geerlingguy.docker/tasks/setup-Debian.yml:29
Task/Handler: Add Docker apt key (alternative for older systems without SNI).
```

**Comment by geerlingguy** [comment]
@jamel-hrt - I specifically ignore 306 because that only works on Red Hat systems (see https://github.com/geerlingguy/ansible-role-docker/blob/master/.ansible-lint). There's an open issue upstream which could use feedback if you also agree: https://github.com/ansible/ansible-lint/issues/497

Thanks!
