### ISSUE TITLE
Install docker-ce-cli & containerd.io

### ISSUE THREAD

**Issue by dkirrane** [geerlingguy/ansible-role-docker#205]
It looks like this role doesn't install `docker-ce-cli` & `containerd.io` packages?
Is there a different role/way to add these?

```
    packages:
    - "docker-ce-{{ docker_version }}"
    - "docker-ce-cli-{{ docker_version }}"
    - containerd.io
```

**Comment by geerlingguy** [comment]
The way this role works it usually just installs a single `docker_package`: https://github.com/geerlingguy/ansible-role-docker/blob/master/tasks/main.yml#L8-L12

I believe that the `docker-ce` package requires the other two, so they are installed automatically. If I'm wrong, we can reopen this issue and look at how to change the behavior...

**Comment by hemberger** [comment]
@geerlingguy The `docker-ce-cli` and `docker-ce-rootless-extras` packages are indeed not updated when this role runs.

For example, here is what I see after the role updates `docker-ce` from 20.10.9 to 20.10.13:
```
$ apt list | grep docker-ce
docker-ce/bionic,now 5:20.10.13~3-0~ubuntu-bionic amd64 [installed]
docker-ce-cli/bionic 5:20.10.13~3-0~ubuntu-bionic amd64 [upgradable from: 5:20.10.9~3-0~ubuntu-bionic]
docker-ce-rootless-extras/bionic 5:20.10.13~3-0~ubuntu-bionic amd64 [upgradable from: 5:20.10.9~3-0~ubuntu-bionic]
```
I would classify this as a bug, because we're still running 20.10.9 on the commandline even after the docker daemon has been restarted:
```
$ docker --version
Docker version 20.10.9, build c2ea9bc
```
The solution looks pretty straightforward, as identified in some of the other issues/PRs on this topic, e.g. https://github.com/geerlingguy/ansible-role-docker/issues/251#issuecomment-910177671 and https://github.com/geerlingguy/ansible-role-docker/pull/297.

Thanks for your time!

**Comment by geerlingguy** [comment]
Sounds good. My proposal would be a PR to change the default `docker_package` to `docker_packages` and have it set to the following:

```yaml
docker_packages:
  - "docker-{{ docker_edition }}"
  - "docker-{{ docker_edition }}-cli"
  - "docker-{{ docker_edition }}-rootless-extras"
```

This would be a breaking change, but once made it should solve this issue.

**Comment by j-koehler** [comment]
I just stumbled across this very same issue when switching from "handcrafted server" to Ansible and wondering why `docker --version` still returns the old version.
