### ISSUE TITLE
Question: why install containerd explicitely on CentOS8

### ISSUE THREAD

**Issue by srmo** [geerlingguy/ansible-role-docker#230]
Ahoi,

thank you for sharing your amazing roles. We are starting to use your docker-role 2.8.2, as it seems to support debian and EL both.
We stumbled upon https://github.com/geerlingguy/ansible-role-docker/blob/5d6af00f205960514f747db1ac7e6980ac31846c/tasks/setup-RedHat.yml#L41 
and we don't understand why you'd need to install containerd manually. Also, why install it from a version 7 repo when you test for version 8?

**Comment by csuka** [comment]
RedHat hasn't made the package available for v8 yet. And this package is a requirement for Docker to work.
So, as a workaround, a manual installation of containerd is required. The CentOS 7 package simply works for CentOS 8.

**Comment by rkm** [comment]
Seems like the packages are now available https://download.docker.com/linux/centos/8/x86_64/stable/Packages/

**Comment by csuka** [comment]
Great! I think you can make a PR.

**Comment by rkm** [comment]
You're welcome to! I've made similar issues and PRs to this repo recently which were marked as stale before being reviewed, so I've ended up just using my own fork.

**Comment by csuka** [comment]
I've commented your review. Once resolved, I hope @geerlingguy will merge it.

**Comment by geerlingguy** [comment]
@csuka - Do you mind linking to where the PR exists?

**Comment by csuka** [comment]
I assumed it was this one:

https://github.com/geerlingguy/ansible-role-docker/pull/224

**Comment by geerlingguy** [comment]
Fixed in https://github.com/geerlingguy/ansible-role-docker/pull/224 (at least the simple changes).

**Comment by geerlingguy** [comment]
Also to shed light on why it was done that way initially—I think I made that change shortly after CentOS 8 came out, and when it did, RHEL was still laser-focused on Podman support to the exclusion of Docker (I think some people were of the opinion that "you have Podman, why would you want to install Docker?"), so the whole containerd thing was not a priority...

Anyways, it seems like the situation has improved since then. I'm not running CentOS 8 in production yet because there are some other annoying things that keep causing me to make major changes to my automation that was not the case with 5-6-7 (the hardest thing in that cycle was really systemd, but since every other distro under the sun also switched to systemd that was not a big deal).

**Comment by srmo** [comment]
Thanks guys! Love your quick response and work on that roles. Keep rocking!
