### ISSUE TITLE
 RedHat/CentOS: No [docker-ce-edge] section in docker-ce.repo.

### ISSUE THREAD

**Issue by jmnotin** [geerlingguy/ansible-role-docker#239]
Hi,

The `docker-ce.repo` file downloaded from Docker does not contain any  `[docker-ce-edge]` section (anymore?). The setting of `docker_yum_repo_enable_edge` then creates an empty section, with neither name nor url.

It is not much of an inconvenience as it does not prevent Docker from installing and setting up correctly. But it makes yum warn about it (`Repository 'docker-ce-edge' is missing name in configuration, using id.`) and makes the option `docker_yum_repo_enable_edge` meaningless.

**Comment by MatthiasHertel** [comment]
same here ... there is no "docker-ce-edge" section anymore on the official yum repo - so that is broken here

https://download.docker.com/linux/centos/docker-ce.repo

@geerlingguy i guess u can remove this ini block see here:

https://github.com/geerlingguy/ansible-role-docker/blob/master/tasks/setup-RedHat.yml#L23

**Comment by nfk** [comment]
You can remove edge channel or replace it by nightly. Available channels are stable, test and nightly.

**Comment by geerlingguy** [comment]
Submitted PR, we'll see if it passes tests. I'll have to do a new major version bump as this changes a parameter (drops the `edge` var and uses new `nightly` one...).
