### ISSUE TITLE
Centos8 runc error

### ISSUE THREAD

**Issue by dhdanno** [geerlingguy/ansible-role-docker#254]
Getting this error on CentOS 8.3

`FAILED! => {"changed": false, "failures": [], "msg": "Depsolve Error occured: \n Problem: problem with installed package podman-2.0.5-5.module_el8.3.0+512+b3b58dca.x86_64\n  - package podman-2.0.5-5.module_el8.3.0+512+b3b58dca.x86_64 requires runc >= 1.0.0-57, but none of the providers can be installed\n  - package containerd.io-1.4.3-3.1.el8.x86_64 conflicts with runc provided by runc-1.0.0-68.rc92.module_el8.3.0+475+c50ce30b.x86_64\n  - package containerd.io-1.4.3-3.1.el8.x86_64 obsoletes runc provided by runc-1.0.0-68.rc92.module_el8.3.0+475+c50ce30b.x86_64\n  - cannot install the best candidate for the job\n  - package runc-1.0.0-64.rc10.module_el8.3.0+479+69e2ae26.x86_64 is filtered out by modular filtering", "rc": 1, "results": []}`

**Comment by dhdanno** [comment]
did this to fix:

`yum remove runc -y`

**Comment by NlVlN** [comment]
Another way is to completely uninstall podman and buildah.

**Comment by shubhambhardwaj007** [comment]
The root cause behind above issue is that both docker and Podman can't be installed on the same Base OS simultaneously. So there exists a conflict between.Centos8(by Redhat) come up with Podman(Redhat product) preinstalled so before installing docker on centos8 you have to first uninstall Podman using following cmd:
> yum remove podman-2.0.5-5.module_el8.3.0+512+b3b58dca.x86_64
Moreover, Its not the error of runc as its common container runtime for both docker and podman.
