### ISSUE TITLE
apt-transport-https was already set to manually installed.

### ISSUE THREAD

**Issue by corburn** [geerlingguy/ansible-role-docker#285]
os: debian sid
role commit: e5c8040aff90e7d8e540bc1439579bc2f78a6543

fatal: [node]: FAILED! => {"changed": false, "msg": "'/usr/bin/apt-mark manual apt-transport-https ca-certificates' failed: E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)\nE: Failed to write temporary StateFile /var/lib/apt/extended_states\n", "rc": 100, "stderr": "E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)\nE: Failed to write temporary StateFile /var/lib/apt/extended_states\n", "stderr_lines": ["E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)", "E: Failed to write temporary StateFile /var/lib/apt/extended_states"], "stdout": "apt-transport-https was already set to manually installed.\n", "stdout_lines": ["apt-transport-https was already set to manually installed."]}

**Comment by gee-forr** [comment]
Howdy...

I just encountered this myself. It's erroring out because the user doesn't have permission to install anything. I run my playbooks as a `deploy` user, and then switch to root ad-hoc as needed.

Call the role in your playbook like so, and you should be good:

```yaml
    - { role: geerlingguy.docker, tags: docker, become: true }
```

The `become: true` runs the entire role as root (assuming your user can sudo). Hope this helps.

**Comment by staticdev** [comment]
@gee-forr I don't think running the whole role as root is recommended from security point-of-view. Although I see in the code, for instance, `apt` steps don't have `become: true`, so probably this is the only way around. I see an inconsistency here, since the documentation put as example playbook using this role without become.

Maybe a PR would be needed to be able this role as a non-root user or adding `become: true` to the example playbook, if this is intentional. Any thoughts on that @geerlingguy?

**Comment by gee-forr** [comment]
> @gee-forr I don't think running the whole role as root is recommended from security point-of-view.

100% agree - I only switch to root on an as-needs basis.

The docs don't use become, because perhaps @geerlingguy builds all his roles to implicitly run as root?

**Comment by geerlingguy** [comment]
You can typically either run a role with `become: true`, or the playbook with `become: true`, but I implicitly assume you'll have a user with privileges to do the operations in my roles—since I deploy to a huge variety of environments, I don't like adding `become` on a task level because it can cause a lot of confusion if you actually _don't_ want a role to try to use sudo (especially in environments where sudo might not be present, like Docker image builds).

**Comment by staticdev** [comment]
@corburn in this case I suggest you try the solution from @gee-forr. Nice to have a comment on README about this implicit assumption we are running as user with all permissions as this behavior can vary in other ansible roles.

**Comment by gee-forr** [comment]
I’ll pop a PR over the weekend for this. Not a big deal.

--

Gabriel Fortuna ***@***.***
