### ISSUE TITLE
Does not install the latest version of Docker engine

### ISSUE THREAD

**Issue by tdoan2010** [geerlingguy/ansible-role-docker#404]
Currently, the [latest version](https://docs.docker.com/engine/release-notes/23.0/) of the Docker engine is `23.0.1`. But when I install Docker using this Ansible role, I only get `20.10.8`.

When I manually follow the instruction about [how to install Docker on Ubuntu](https://docs.docker.com/engine/install/ubuntu/), I got the latest version.

Did I miss any configuration of this role? I suppose it always install the latest version of Docker, but it was not the case.

**Comment by pagdot** [comment]
Seems like that is a limitation how package managers handle the install command and that ansibles package module doesn't upgrade packages, just makes sure any version of them is installed. See [tasks/main.yml#L19-L34) for reference. According to the [package module documentations `state` parameter](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html#parameter-state) at least with some package managers it is supported to set the `state` to `latest` to get the latest version of a package.

This ansible role would support this by setting the variable `docker_packages_state` to `latest` instead of the default `present`. This could be added to the documentation of the role.
