### ISSUE TITLE
Install docker-buildx-plugin option?

### ISSUE THREAD

**Issue by rltas** [geerlingguy/ansible-role-docker#405]
I believe similar to `docker_install_compose_plugin`, it would make sense to have an option `docker_install_buildx_plugin` to install `docker-buildx-plugin`?
I ran into an issue where it was missing when deploying the Matrix Ansible Playbook on an Ubuntu 22.04 LTS host with `APT::Install-Recommends "false";`.

**Comment by danielwoodz** [comment]
This is probably due to a [change in docker 23.0](https://docs.docker.com/engine/release-notes/23.0/). buildx is no longer included with docker-cli. When docker version is >= 23, you need to also install `docker-buildx-plugin`

You can fix this by overriding the default package list in your inventory:
```yaml
docker_packages:
  - "docker-ce"
  - "docker-ce-cli"
  - "docker-ce-rootless-extras"
  - "docker-buildx-plugin"
  - "containerd.io"
  ```
