### ISSUE TITLE
getting 'Could not find the requested service docker: host'

### ISSUE THREAD

**Issue by developerinlondon** [geerlingguy/ansible-role-docker#42]
It seems that we are looking for a docker service that is nonexistant. 

I am testing this in a docker container 'centos:7'. so it fails on line `/geerlingguy.docker/tasks/main.yml:11`

any ideas? Docker in Docker should not cause issues right?

**Comment by JCorson** [comment]
Possibly related to https://github.com/ansible/ansible/issues/36585?

**Comment by geerlingguy** [comment]
I haven't seen this issue in any of my builds, but if I'm running docker in docker, I use my own Docker images which have an entire setup around systemd running inside the container to make the container more like a typical/traditional VM.

I'm guessing the `centos:7` Docker image doesn't ship with a full fledged systemd setup, because that's not the typical Docker way of doing things.

But this would definitely be something to approach upstream as it's not something this role can fix, since it relies on the `service` module.

However, if you're using this role to install Docker inside a Docker container, it's best to not try starting Docker as part of the role setup... and to that end, I'm going to set the service state to a variable (https://github.com/geerlingguy/ansible-role-docker/blob/master/tasks/main.yml#L17).

**Comment by danihodovic** [comment]
This can be reproduced with `solita/ubuntu-systemd:18.04` as the base image.

**Comment by bbaassssiiee** [comment]
It's still an issue.
